### GET /user
GET http://localhost:3000/users

### GET /user/:userId
GET http://localhost:3000/users/625dabb165e46b13c85e6165

### POST /user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "TestUser",
  "about": "kjsndkjsnd",
  "avatar": "https://avatarko.ru/img/kartinka/33/multfilm_lyagushka_32117.jpg"
}

### PATCH /users/me
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Тестовый пользователь",
  "about": "mtlmlkmknk"
}

### PATCH /users/me/avatar
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar": "https://papik.pro/uploads/posts/2021-12/thumbs/1640708490_3-papik-pro-p-milota-risunki-anime-3.jpg"
}

### GET /cards
GET http://localhost:3000/cards

### POST /cards
POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "Первая карточка",
  "link": "https://avatarko.ru/img/kartinka/11/multfilm_Simpsons_10262.jpg"
}

### DELETE /cards/:cardId
DELETE  http://localhost:3000/cards/625f4e4701cd8e0269437454

### PUT /cards/:cardId/likes
PUT http://localhost:3000/cards/625ed053259de25fc5bea46e/likes


### DELETE /cards/:cardId/likes
DELETE  http://localhost:3000/cards/625ed053259de25fc5bea46e/likes

###
GET https://mesto.nomoreparties.co/v1/cohort-34/cards
authorization: f9818e95-aa05-4a44-a493-1bf7e5072c11
